<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>4.0.6</version>
    </parent>

    <groupId>com.ibby.hub</groupId>
    <artifactId>finance-split</artifactId>
    <version>1.0-SNAPSHOT</version>

    <packaging>pom</packaging>

    <properties>
        <java.version>25</java.version>
        <spring.boot.version>4.0.6</spring.boot.version>
        <spring.security.version>6.5.1</spring.security.version>
        <spring.framework.version>7.0.5</spring.framework.version>

        <db.postgres.version>42.7.10</db.postgres.version>
        <flyway.core.version>12.6.0</flyway.core.version>

        <log4j.version>2.0.7</log4j.version>
        <spring.doc.openapi.version>3.0.3</spring.doc.openapi.version>
        <mockito.version>4.5.1</mockito.version>
        <hibernate-persistence.version>3.2.0</hibernate-persistence.version>
        <jackson.version>2.15.3</jackson.version>
        <swagger.annotations.jakarta.version>2.2.49</swagger.annotations.jakarta.version>

        <node.version>v24.11.1</node.version>
        <node.root>https://nodejs.org/dist/</node.root>
        <angular.version>21.2.9</angular.version>
        <frontend.maven.plugin.version>1.9.1</frontend.maven.plugin.version>


        <maven.compiler.plugin.version>3.14.1</maven.compiler.plugin.version>
        <maven.jar.plugin.version>3.4.2</maven.jar.plugin.version>
        <maven.clean.plugin.version>3.1.0</maven.clean.plugin.version>
        <openapi.generator.maven.plugin.version>7.22.0</openapi.generator.maven.plugin.version>
    </properties>

    <modules>
        <module>finance-split-api</module>
        <module>finance-split-domain</module>
        <module>finance-split-domainservice</module>
        <module>finance-split-rest</module>
        <module>finance-split-openapi-spec</module>
        <module>finance-split-server</module>
        <module>finance-split-client</module>
    </modules>

    <dependencyManagement>
        <dependencies>
            <!-- SPRING -->
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-starter-security</artifactId>
            </dependency>
            <dependency>
                <groupId>org.springframework</groupId>
                <artifactId>spring-framework-bom</artifactId>
                <version>${spring.framework.version}</version>
            </dependency>
            <dependency>
                <groupId>org.springdoc</groupId>
                <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
                <version>${spring.doc.openapi.version}</version>
            </dependency>

            <!-- OTHER -->
            <dependency>
                <groupId>org.mockito</groupId>
                <artifactId>mockito-core</artifactId>
                <version>${mockito.version}</version>
            </dependency>
            <dependency>
                <groupId>org.slf4j</groupId>
                <artifactId>slf4j-log4j12</artifactId>
                <version>${log4j.version}</version>
            </dependency>
            <dependency>
                <groupId>io.swagger.core.v3</groupId>
                <artifactId>swagger-models-jakarta</artifactId>
                <version>${swagger.annotations.jakarta.version}</version>
            </dependency>
            <dependency>
                <groupId>io.swagger.core.v3</groupId>
                <artifactId>swagger-annotations-jakarta</artifactId>
                <version>${swagger.annotations.jakarta.version}</version>
                <scope>runtime</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <pluginManagement>
            <plugins>
                <!-- backend -->
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>${maven.compiler.plugin.version}</version>
                </plugin>
                <plugin>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-maven-plugin</artifactId>
                    <version>${spring.boot.version}</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-jar-plugin</artifactId>
                    <version>${maven.jar.plugin.version}</version>
                </plugin>

                <!-- client -->
                <plugin>
                    <artifactId>maven-clean-plugin</artifactId>
                    <version>${maven.clean.plugin.version}</version>
                </plugin>
                <plugin>
                    <groupId>org.openapitools</groupId>
                    <artifactId>openapi-generator-maven-plugin</artifactId>
                    <version>${openapi.generator.maven.plugin.version}</version>
                </plugin>
                <plugin>
                    <groupId>com.github.eirslett</groupId>
                    <artifactId>frontend-maven-plugin</artifactId>
                    <version>${frontend.maven.plugin.version}</version>
                </plugin>

                <!-- openapi spec -->
                <plugin>
                    <groupId>org.codehaus.mojo</groupId>
                    <artifactId>build-helper-maven-plugin</artifactId>
                    <version>3.4.0</version>
                </plugin>
                <plugin>
                    <groupId>org.springdoc</groupId>
                    <artifactId>springdoc-openapi-maven-plugin</artifactId>
                    <version>1.0</version>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>
</project>
