server.port=8080
spring.application.name=finance-split-backend
# DB
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO}
# FLYWAY
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.validate-migration-naming=true
spring.flyway.locations=classpath:db/migration
# actuator
management.endpoint.health.probes.enabled=true
management.health.livenessState.enabled=true
management.health.readinessState.enabled=true
