<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>com.ibby.hub</groupId>
    <artifactId>finance-split</artifactId>
    <version>1.0-SNAPSHOT</version>
  </parent>

  <artifactId>finance-split-client</artifactId>

  <dependencies>
    <dependency>
      <groupId>com.ibby.hub</groupId>
      <artifactId>finance-split-openapi-spec</artifactId>
      <version>1.0-SNAPSHOT</version>
      <scope>provided</scope>
    </dependency>
  </dependencies>

  <profiles>
    <profile>
      <id>npm install and build</id>
      <activation>
        <activeByDefault>true</activeByDefault>
      </activation>
      <build>
        <resources>
          <resource>
            <directory>target/build-angular</directory>
          </resource>
        </resources>
        <plugins>
          <plugin>
            <artifactId>maven-clean-plugin</artifactId>
            <configuration>
              <filesets>
                <fileset>
                  <directory>src/app/core/core-api</directory>
                </fileset>
              </filesets>
            </configuration>
          </plugin>
          <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-dependency-plugin</artifactId>
            <executions>
              <execution>
                <id>unpack</id>
                <phase>initialize</phase>
                <goals>
                  <goal>unpack</goal>
                </goals>
                <configuration>
                  <artifactItems>
                    <artifactItem>
                      <groupId>com.ibby.hub</groupId>
                      <artifactId>finance-split-openapi-spec</artifactId>
                      <version>${project.version}</version>
                    </artifactItem>
                  </artifactItems>
                </configuration>
              </execution>
            </executions>
          </plugin>
          <plugin>
            <artifactId>maven-jar-plugin</artifactId>
            <configuration>
              <archive>
                <compress>false</compress>
              </archive>
            </configuration>
          </plugin>
          <plugin>
            <groupId>org.openapitools</groupId>
            <artifactId>openapi-generator-maven-plugin</artifactId>
            <executions>
              <execution>
                <id>generate-angular-client</id>
                <phase>none</phase>
                <goals>
                  <goal>generate</goal>
                </goals>
              </execution>
              <execution>
                <id>generate-test-client</id>
                <phase>none</phase>
                <goals>
                  <goal>generate</goal>
                </goals>
              </execution>
              <execution>
                <id>generate</id>
                <goals>
                  <goal>generate</goal>
                </goals>
                <configuration>
                  <inputSpec>${project.build.directory}/dependency/openapi.json</inputSpec>
                  <generatorName>typescript-angular</generatorName>
                  <output>src/app/core/core-api</output>
                  <additionalProperties>
                    <additionalProperty>ngVersion=${angular.version}</additionalProperty>
                  </additionalProperties>
                  <configOptions>
                    <enumPropertyNaming>UPPERCASE</enumPropertyNaming>
                  </configOptions>
                  <typeMappings>
                    <!-- since `Set` is not a JSON type -->
                    <typeMapping>set=Array</typeMapping>
                  </typeMappings>
                </configuration>
              </execution>
            </executions>
          </plugin>
          <plugin>
            <groupId>com.github.eirslett</groupId>
            <artifactId>frontend-maven-plugin</artifactId>
            <version>${frontend.maven.plugin.version}</version>
            <executions>
              <execution>
                <id>install node and npm</id>
                <goals>
                  <goal>install-node-and-npm</goal>
                </goals>
              </execution>
              <execution>
                <id>npm install</id>
                <goals>
                  <goal>npm</goal>
                </goals>
                <configuration>
                  <arguments>install</arguments>
                </configuration>
              </execution>
              <execution>
                <id>build</id>
                <goals>
                  <goal>npm</goal>
                </goals>
                <configuration>
                  <arguments>run build</arguments>
                </configuration>
              </execution>
            </executions>
            <configuration>
              <nodeVersion>${node.version}</nodeVersion>
              <installDirectory>target/</installDirectory>
              <nodeDownloadRoot>${node.root}</nodeDownloadRoot>
            </configuration>
          </plugin>
        </plugins>
      </build>
    </profile>
    <profile>
      <id>lint-angular</id>
      <activation>
        <activeByDefault>false</activeByDefault>
      </activation>
      <build>
        <plugins>
          <plugin>
            <groupId>com.github.eirslett</groupId>
            <artifactId>frontend-maven-plugin</artifactId>
            <version>${frontend.maven.plugin.version}</version>
            <executions>
              <execution>
                <id>install node</id>
                <goals>
                  <goal>install-node-and-npm</goal>
                </goals>
              </execution>
            </executions>
            <configuration>
              <nodeVersion>${node.version}</nodeVersion>
              <installDirectory>target/</installDirectory>
              <nodeDownloadRoot>${node.root}</nodeDownloadRoot>
            </configuration>
          </plugin>
        </plugins>
      </build>
    </profile>
  </profiles>
</project>
